### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire() in Laravel 5.8

### ISSUE THREAD

**Issue by babulal107** [asahasrabuddhe/laravel-api#32]
I am trying to implement this package with laravel 5.8 But getting this error "Call to undefined method Illuminate\Events\Dispatcher:: fire() in Laravel 5.8".
I think fire() method has deprecated and removed in laravel 5.8 version.

**Comment by asahasrabuddhe** [comment]
Fixed with commit ID 84d0ba078faf402dd2c12b4cc6b19c9bc063d518
